Deploy templates: fix updating steps in Python 3
If a step in a deploy template is updated, changing only the step's
'args' field, then we see the following error on Python 3:

TypeError: unorderable types: dict() < dict()

In Python 3, dicts are no longer orderable, so cannot be used as part of
the key to a sort function. This change uses a JSON dump of the step
with sorted keys for comparison, as suggested in [1].

[1] https://stackoverflow.com/a/22003440

Change-Id: I70b806d5850f0678f3dd6633228947f6cd39d691
Story: 1722275
Task: 29750