Use standard locale when executing 'dd' command
When executing 'dd' command, baremetal provisioning fails on OS with
Japanese because of ascii codec error:
 InstanceDeployFailure: Deploy failed for instance <uuid>.
 Error: 'ascii' codec can't decode byte 0xc2 in position 24:
        ordinal not in range(128)
This patch set fixes this bug by using standard locale when
executing 'dd'.

Change-Id: I8107975044cc9dec85e0d7571f99eaf5ea869891
Closes-Bug:#1488289
Co-Authored-By: Ruby Loo <rloo@yahoo-inc.com>
(cherry picked from commit 8166c6e8ddd333ee9930d0d7d1afb7c2ee47fc4a)