Retry stdlib ssl.SSLError
Apparently, connection to the agent can fail with

    Unexpected error when processing next clean step.
    SSLError: ('timed out',): ssl.SSLError: ('timed out',)

This change adds SSLError to retriable errors since most of them are
related to temporary conditions, and the certificate validation failure
is handled by requests separately.

Change-Id: I4805d410b4bc98196e77d8c44a217e363dc88f0a