Fix `snmp` unit test
Under some condition, some code underneath `snmp` power driver
seems to call `sleep` for its own reason. That fails sleep
mock call assertion:

    AssertionError: Expected 'sleep' to be called once. Called 8 times.
    Calls: [call(0), call(0), call(0), ... call(0), call(5)].

This fix asserts just the sleep call we expect.

Change-Id: I2edec4cbea2d39910f1fb52b0373169c03a4ec0d