Fix Redfish jobs by pinning sushy-tools
Sushy-tools pulls in master branch by default based
on the job configuration, however we recently merged
support into sushy-tools which requires a version of
ironic-lib, which is unavailable to this system resulting
in an exception.

File "/opt/stack/sushy-tools/sushy_tools/emulator/main.py", line 24, in <module>
  from ironic_lib import auth_basic
ImportError: cannot import name 'auth_basic'

*Also* Temporarily disables the grub2 jobs to allow multiple
fixes to be merged in sequence.

Change-Id: Ie8c10db135a77bd4cc2e17a266a45cca65100199