Update minimum requirements for ilo drivers
The proliantutils version needed is updated to 2.13.0
When running tests with older versions we get the error:
AttributeError: None does not have the attribute 'IloClient'

Change-Id: I6ab0672679c9d929c1e7c43a5966e6ad1e5353c0
Co-Authored-By: Thomas Goirand <thomas@goirand.fr>