Fix idrac-wsman RAID apply_configuration
Deploy step `apply_configuration` was failing with
TypeError: super(type, obj): obj must be an instance
or subtype of type.

Change-Id: I4de034c38585275543ab603a3ed45de1adf1d15b
Story: 2007963
Task: 40456
(cherry picked from commit 328cb9291a8c19d18321fde1e2323f4682363789)