Update dev-quickstart: interval value cannot be -1
This updates the documentation to set the sync_power_state_interval
to a large number instead of -1. Using -1 results in the error

ValueError: Periodicity/spacing must be greater than zero instead of -1

-1 used to work until we started using the futurist/periodics code.

Change-Id: I1eb95345f8746a6ac7b97352bdeb20ca33e9434c